name: Docker Image Build and Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
            version: v0.12.0
            driver-opts: |
                image=moby/buildkit:v0.12.0

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/ros2_agri_project:latest
            ghcr.io/${{ github.repository_owner }}/ros2_agri_project:${{ github.run_number }}-test
          build-args: |
            ROS_DISTRO=jazzy

      # Step 5: Run basic tests
      - name: Run Tests
        run: |
          docker run \
            --rm \
            ghcr.io/${{ github.repository_owner }}/ros2_agri_project:${{ github.run_number }}-test bash -c "source /opt/ros/jazzy/setup.bash && source /root/ros2_ws/install/setup.bash && colcon test"